### ISSUE TITLE
invalid-token error

### ISSUE THREAD

**Issue by develper1** [xvilo/harvest-forecast#4]
I am using correct token and account ID of harvest. I am using same for restAPI that token and account ID working but in the forecast getting error invalid token. 

I used toke with Bearer and without Bearer as well.. but didn't work. 

I am running project PHP 8.0.3 independently.

I need to get project list from Harvest forecast. 

kindly guide me what is issue. 
@xvilo @samuele-mattiuzzo

**Comment by samuele-mattiuzzo** [comment]
Have you tried what's suggested [here](https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/) ? You should have 2 different IDs, one for harvest and one for forecast. Try those curl-based API calls first, and if they work, the same should work with this package

**Comment by develper1** [comment]
Thanks for your response. 

Do you mean OAuth2  token I use that one but this client ID is not an integer?
I tried with these both but its didn't work.

Do you have any example running?

These are new OAuth2 keys.
![image](https://user-images.githubusercontent.com/76731493/122912221-86b97b80-d371-11eb-81d2-1f1a171ca0d6.png)

**Comment by samuele-mattiuzzo** [comment]
The examples are linked in my previous response, you can try those with your API keys. I'd suggest also to not share those API keys (luckily the screenshots you tried posting are empty)

**Comment by develper1** [comment]
I will remove the key its sandbox account.
![image](https://user-images.githubusercontent.com/76731493/122916237-1c570a00-d376-11eb-8761-f221fa542444.png)

Are you using OAuth keys or Access token?

**Comment by develper1** [comment]
these two types keys I tried..
![image](https://user-images.githubusercontent.com/76731493/122916541-7061ee80-d376-11eb-90b1-256f4116239a.png)

**Comment by xvilo** [comment]
@develper1 did you found out what was causing the issue? For now only `Personal Access Tokens` are supported. Are you 100% sure the code is correct?

Make sure that
- Your token is correct in your application
- You've correctly set the correct `account`
- You're using the right `account ID`

**Comment by xvilo** [comment]
As there wasn't any response, I'll be closing the issue
